Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
    v.linked_clone = true
  end
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.provision "shell" do |s|
    s.inline = "cp /vagrant/*.sh /home/vagrant/; chmod +x /home/vagrant/*.sh"
  end
end
